### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by h404bi** [egoist/saber#27]
```
$ yarn create blog demo
...
$ yarn dev
yarn run v1.13.0
$ saber
Built at: 2019-03-09 15:03:40
Entrypoint client [big] = js/client.js js/client.js.map

ERROR in ./pages/about.vue?vue&type=custom&index=0&blockType=extend-component&saberPage=7291c502 (./node_modules/saber/lib/renderer/extend-component-loader.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/saber/lib/renderer/saber-page-loader.js??ref--2-1!./pages/about.vue?vue&type=custom&index=0&blockType=extend-component&saberPage=7291c502)
Module not found: Error: Can't resolve 'C:Usershanabi   mpdemopagesabout.vue' in 'C:\Users\hanabi\tmp\demo\pages'
 @ ./pages/about.vue?vue&type=custom&index=0&blockType=extend-component&saberPage=7291c502 (./node_modules/saber/lib/renderer/extend-component-loader.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/saber/lib/renderer/saber-page-loader.js??ref--2-1!./pages/about.vue?vue&type=custom&index=0&blockType=extend-component&saberPage=7291c502) 7:0-68 11:17-30
 @ ./pages/about.vue?vue&type=custom&index=0&blockType=extend-component&saberPage=7291c502
 @ ./pages/about.vue?saberPage=7291c502
 @ ./.saber/routes.js
 @ ./node_modules/saber/lib/renderer/app/create-app.js
 @ ./node_modules/saber/lib/renderer/app/entry-client.js
 @ multi (webpack)-hot-middleware/client.js ./node_modules/saber/lib/renderer/app/entry-client.js
```

**Comment by egoist** [comment]
Thanks for reporting this, will fix it later.

**Comment by egoist** [comment]
Should be fixed in `0.2.13`

**Comment by h404bi** [comment]
@egoist I'm afraid not 🤣 
![sc](https://user-images.githubusercontent.com/5764917/54410016-9ffc0800-4724-11e9-9f96-9564d600f75d.png)

**Comment by h404bi** [comment]
still encounter this issue in saber@latest (saber@0.2.20), is there any other information I should provide for you to investigate this?

**Comment by egoist** [comment]
0.2.21 should work
